
api:
  id: "![6Kcmi/rpmTii8UrJZoifDg==]"

keystore:
  password: "![JjY9qam5f/5g/e2ov11kBQ/LSV+Fz959AOXoaSJ33V4=]"  

database:
  host: "![wXUxzYMnC7OuLSFlMw6hX5teeqVClkcFJdR9bvgqkXeKk7iWPeBHOaWJgjNGWoj9]"
  username: "![y4q8deMrIz2a4OLzK78GYKOfghT3hoqCEQdvlIEtlFc=]"
  password: "![VyY3a41XBHvCIyYsvphlhQ==]"  
  port: "![hADE5G9F79cFBK856/O/UQ==]"